<?xml version="1.0"?>
<robot name="four_wheel_car" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Properties -->
  <xacro:property name="wheel_radius" value="0.1" />
  <xacro:property name="wheel_width" value="0.05" />
  <xacro:property name="base_length" value="0.6" />
  <xacro:property name="base_width" value="0.4" />
  <xacro:property name="wheel_offset" value="0.05" />

  <!-- Materials -->
  <material name="black">
    <color rgba="0.0 0.0 0.0 1.0" />
  </material>

  <!-- Links -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.6 0.4 0.1" />
      </geometry>
      <origin xyz="0 0 0.05" />
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <box size="0.6 0.4 0.1" />
      </geometry>
      <origin xyz="0 0 0.05" />
    </collision>
    <inertial>
      <mass value="10.0" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
    </inertial>
  </link>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="name x y z">
    <link name="${name}_link">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 ${pi / 2} 0" />
        <material name="black" />
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
        <origin xyz="0 0 ${wheel_width / 2}" rpy="0 ${pi / 2} 0" />
      </collision>
      <inertial>
        <mass value="1.0" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
      </inertial>
    </link>

    <!-- Wheel Joint -->
    <joint name="${name}_steering_joint" type="continuous">
      <parent link="base_link" />
      <child link="${name}_link" />
      <origin xyz="${x} ${y} ${z}" />
      <axis xyz="0 0 1" />
    </joint>

    <joint name="${name}_drive_joint" type="revolute">
      <parent link="${name}_link" />
      <child link="${name}_tire" />
      <origin xyz="0 0 ${wheel_width / 2}" />
      <axis xyz="1 0 0" />
    </joint>

    <link name="${name}_tire">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 ${pi / 2} 0" />
        <material name="black" />
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 ${pi / 2} 0" />
      </collision>
    </link>
  </xacro:macro>

  <!-- Front Left Wheel -->
  <xacro:wheel name="front_left" x="${base_length / 2}" y="${base_width / 2}" z="${wheel_offset}" />

  <!-- Front Right Wheel -->
  <xacro:wheel name="front_right" x="${base_length / 2}" y="-${base_width / 2}" z="${wheel_offset}" />

  <!-- Rear Left Wheel -->
  <xacro:wheel name="rear_left" x="-${base_length / 2}" y="${base_width / 2}" z="${wheel_offset}" />

  <!-- Rear Right Wheel -->
  <xacro:wheel name="rear_right" x="-${base_length / 2}" y="-${base_width / 2}" z="${wheel_offset}" />

  <!-- Gazebo Plugins -->
  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <robotNamespace>/</robotNamespace>
      <controlPeriod>0.01</controlPeriod>
    </plugin>
  </gazebo>

  <gazebo reference="base_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="front_left_tire">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1.0e3</kp>
    <kd>1.0</kd>
  </gazebo>

  <gazebo reference="front_right_tire">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1.0e3</kp>
    <kd>1.0</kd>
  </gazebo>

  <gazebo reference="rear_left_tire">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1.0e3</kp>
    <kd>1.0</kd>
  </gazebo>

  <gazebo reference="rear_right_tire">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>1.0e3</kp>
    <kd>1.0</kd>
  </gazebo>

</robot>
